name = "parentsintech-org"
main = "@astrojs/cloudflare/entrypoints/server"
account_id = "6d2e606929eb69f91f43b147615f1111"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
routes = [{ pattern = "parentsintech.org/*", zone_name = "parentsintech.org" }]

# Asset handling
[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

# Production env
[env.production]
name = "parentsintech-org-prod"
route = "parentsintech.org/*"
